services:
  - type: web
    name: shopswift-api
    runtime: docker
    plan: free
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: shopswift-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: shopswift-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: shopswift-db
          property: password

databases:
  - name: shopswift-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "18"
    databaseName: shopswift_db
    user: shopswift_user
    ipAllowList: []
